apiVersion: v1
kind: Service
metadata:
  name: selenosis
  namespace: selenosis
  {{- if .Values.aks.enabled }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: {{ default "true" .Values.aks.useInternalAzureLoadBalancer | quote }}
  {{- end }}
spec:
  externalTrafficPolicy: {{ default "Cluster" .Values.externalTrafficPolicy }}
  ports:
  - name: selenium
    port: 4444
    protocol: TCP
    targetPort: 4444
    nodePort: 31000
  selector:
    app: selenosis
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: seleniferous
  namespace: selenosis
spec:
  selector:
    type: browser
  clusterIP: None
  publishNotReadyAddresses: true
  