{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: selenosis
  namespace: selenosis
spec:
  maxReplicas: {{ .Values.autoscaling.maxReplicas }} # define max replica count
  minReplicas: {{ .Values.autoscaling.minReplicas }}  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: selenosis
  # targetCPUUtilizationPercentage: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.stabilizationWindowInSeconds }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.scaleDownPercentage }}
        periodSeconds: {{ .Values.autoscaling.scaleDownPeriodInSeconds }}
{{- end }}
