{{- if .Values.selenoidUI.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid-ui
  namespace: selenosis
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: selenoid-ui
  template:
    metadata:
      labels:
        app: selenoid-ui
        selenosis.app.type: worker
      namespace: selenosis
    spec:
      containers:
        - args: ["--status-uri", "http://localhost:4444", "-webdriver-uri", "http://selenosis:4444"]
          name: selenoid-ui
          imagePullPolicy: IfNotPresent
          image: {{ .Values.selenoidUI.image.registry }}/{{ .Values.selenoidUI.image.image }}:{{ .Values.selenoidUI.image.tag }}
          resources:
            {{- toYaml .Values.selenoidUI.resources | nindent 12 }}       
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
        - args: ["--port", ":4444", "--selenosis-url", "http://selenosis:4444"]
          name: selenoid-ui-adapter
          imagePullPolicy: IfNotPresent
          image: {{ .Values.selenoidUIAdapter.image.registry }}/{{ .Values.selenoidUIAdapter.image.image }}:{{ .Values.selenoidUIAdapter.image.tag }}
          resources:
            {{- toYaml .Values.selenoidUIAdapter.resources | nindent 12 }} 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui
  namespace: selenosis
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: selenoid-ui
      port: 8080
      targetPort: 8080
      nodePort: 32000
      protocol: TCP
  selector:
    app: selenoid-ui
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
{{- end }}
